const dataweek1 = [
    {
        id: 1,
        number: 1,
        picture: "harold.png",
        name: "Harold",
        points: "6:45",
    },
    {
        id: 2,
        number: 2,
        picture: "laszlo.png",
        name: "Laszlo",
        points: "6:51",
    },
    {
        id: 3,
        number: 3,
        picture: "goadie.png",
        name: "Goadie",
        points: "7:26",
    },
    {
        id: 4,
        number: 4,
        picture: "andy.png",
        name: "Andy",
        points: "7:38",
    },
    {
        id: 5,
        number: 5,
        picture: "yuzpe.png",
        name: "Yuzpe",
        points: "7:40",
    },
    {
        id: 6,
        number: 6,
        picture: "frankie.png",
        name: "Frankie",
        points: "7:47",
    },
    {
        id: 7,
        number: 7,
        picture: "ryan.png",
        name: "Ryan",
        points: "7:50",
    },
    {
        id: 8,
        number: 8,
        picture: "rutu.png",
        name: "Rutu",
        points: "7:57",
    },
    {
        id: 9,
        number: 9,
        picture: "sameer.png",
        name: "Sameer",
        points: "7:58",
    },
    {
        id: 10,
        number: 10,
        picture: "zach.png",
        name: "Zach",
        points: "8:00",
    },
    {
        id: 11,
        number: 11,
        picture: "paarth.png",
        name: "Paarth",
        points: "8:02",
    },
    {
        id: 12,
        number: 12,
        picture: "jacob.png",
        name: "Jacob",
        points: "8:33",
    },
    {
        id: 13,
        number: 13,
        picture: "gonzo.png",
        name: "Gonzo",
        points: "8:40",
    },
    {
        id: 14,
        number: 14,
        picture: "tommy.png",
        name: "Tommy",
        points: "🤕",
    },
    {
        id: 15,
        number: 15,
        picture: "shaurya.png",
        name: "Shaurya",
        points: "🤕",
    },
    {
        id: 16,
        number: 16,
        picture: "morkel.png",
        name: "Morkel",
        points: "🤕",
    },
    {
        id: 17,
        number: 17,
        picture: "sankalp.png",
        name: "Sankalp",
        points: "🤕",
    },
    {
        id: 18,
        number: 18,
        picture: "sherif.png",
        name: "Sherif",
        points: "∞",
    }
]


export default dataweek1;