const data = [
    {
        id: 1,
        number: 1,
        picture: "harold.png",
        name: "Harold",
        points: 25,
    },
    {
        id: 2,
        number: 2,
        picture: "laszlo.png",
        name: "Laszlo",
        points: 20,
    },
    {
        id: 3,
        number: 3,
        picture: "goadie.png",
        name: "Goadie",
        points: 16,
    },
    {
        id: 4,
        number: 4,
        picture: "andy.png",
        name: "Andy",
        points: 13,
    },
    {
        id: 5,
        number: 5,
        picture: "yuzpe.png",
        name: "Yuzpe",
        points: 11,
    },
    {
        id: 6,
        number: 6,
        picture: "frankie.png",
        name: "Frankie",
        points: 10,
    },
    {
        id: 7,
        number: 7,
        picture: "ryan.png",
        name: "Ryan",
        points: 9,
    },
    {
        id: 8,
        number: 8,
        picture: "rutu.png",
        name: "Rutu",
        points: 8,
    },
    {
        id: 9,
        number: 9,
        picture: "sameer.png",
        name: "Sameer",
        points: 7,
    },
    {
        id: 10,
        number: 10,
        picture: "zach.png",
        name: "Zach",
        points: 6,
    },
    {
        id: 11,
        number: 11,
        picture: "paarth.png",
        name: "Paarth",
        points: 5,
    },
    {
        id: 12,
        number: 12,
        picture: "jacob.png",
        name: "Jacob",
        points: 4,
    },
    {
        id: 13,
        number: 13,
        picture: "gonzo.png",
        name: "Gonzo",
        points: 3,
    },
    {
        id: 14,
        number: 14,
        picture: "tommy.png",
        name: "Tommy",
        points: "🤕",
    },
    {
        id: 15,
        number: 15,
        picture: "shaurya.png",
        name: "Shaurya",
        points: "🤕",
    },
    {
        id: 16,
        number: 16,
        picture: "morkel.png",
        name: "Morkel",
        points: "🤕",
    },
    {
        id: 17,
        number: 17,
        picture: "sankalp.png",
        name: "Sankalp",
        points: "🤕",
    },
    {
        id: 18,
        number: 18,
        picture: "sherif.png",
        name: "Sherif",
        points: 0,
    }
]


export default data;